### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by NSElvis** [hyperoslo/hyper-json-form-angular-example#3]
What about renaming the project to

`ng-form`

Or `form-angular`?

**Comment by fespinoza** [comment]
I guess this discussion is over, in any case, the real angular package will be extracted from this side-example-project

**Comment by jgorset** [comment]
I'm gonna need you to agree again, @sindrenm.

**Comment by sindrenm** [comment]
We'll be prefixing stuff with _hyper_. No more questions.

**Comment by jgorset** [comment]
:+1:
